version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.12.0
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout 
      - run:
          name: Install depencies 
          command: npm install
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Build the project 
                command: npm run build 
            - run:
                name: Deploy to github pages 
                command: gh-pages -d dist 
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
